<a href="https://colab.research.google.com/github/kivvgsr/deep-learning/blob/main/BERT_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip uninstall tensorflow tensorflow-text tensorflow-hub -y


Found existing installation: tensorflow 2.16.1
Uninstalling tensorflow-2.16.1:
  Successfully uninstalled tensorflow-2.16.1
Found existing installation: tensorflow-text 2.16.1
Uninstalling tensorflow-text-2.16.1:
  Successfully uninstalled tensorflow-text-2.16.1
Found existing installation: tensorflow-hub 0.16.1
Uninstalling tensorflow-hub-0.16.1:
  Successfully uninstalled tensorflow-hub-0.16.1


In [2]:
!pip install tensorflow tensorflow-text tensorflow-hub


  Using cached tensorflow-2.16.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (589.8 MB)
  Using cached tensorflow_text-2.16.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.2 MB)
  Using cached tensorflow_hub-0.16.1-py2.py3-none-any.whl (30 kB)


In [3]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text  # Import TensorFlow Text



In [4]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [6]:
# create a hub  layer

bert_preprocesse_model = hub.KerasLayer(preprocess_url)
# layer 1

In [ ]:
text_test = ['i love python programming ',"nice movie ","i love you"]
text_preprocessed = bert_preprocesse_model(text_test)
text_preprocessed

In [9]:
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [ ]:
text_preprocessed['input_mask']

In [11]:
# lets create another layer .


bert_encoding_model = hub.KerasLayer(encoder_url)
# layer 2

In [13]:
result = bert_encoding_model(text_preprocessed)

In [14]:
result.keys()

dict_keys(['sequence_output', 'pooled_output', 'encoder_outputs', 'default'])

In [15]:
result['pooled_output'] # this will give the embading for the entire sentence .

<tf.Tensor: shape=(3, 768), dtype=float32, numpy=
array([[-9.1712308e-01, -4.7935188e-01, -7.8656971e-01, ...,
        -6.1751729e-01, -7.1026874e-01,  9.2184299e-01],
       [-8.2308012e-01, -3.3021709e-01,  5.8038939e-02, ...,
         1.5002133e-01, -5.3048509e-01,  8.4959561e-01],
       [-9.1058314e-01, -3.5070521e-01, -3.2318339e-01, ...,
        -4.5049004e-05, -7.1246207e-01,  9.1118830e-01]], dtype=float32)>

3 hence we can use this vectors in our NLP for movie review classification .

In [16]:
result['sequence_output'] # it will give individual word embading vector

# we perform padding hence we use 128

<tf.Tensor: shape=(3, 128, 768), dtype=float32, numpy=
array([[[-0.07900573,  0.36335105, -0.21101636, ..., -0.17183766,
          0.16299722,  0.6724264 ],
        [ 0.27883533,  0.43716174, -0.35764766, ..., -0.04463656,
          0.3831523 ,  0.5887985 ],
        [ 1.2037663 ,  1.0727005 ,  0.48408723, ...,  0.24921016,
          0.40730962,  0.40481848],
        ...,
        [ 0.08630043,  0.1935382 ,  0.47540027, ...,  0.18880142,
         -0.06474131,  0.3131855 ],
        [ 0.15887073,  0.28572664,  0.37340802, ...,  0.09309121,
         -0.04969536,  0.38761148],
        [-0.08079805, -0.09572835,  0.26809752, ...,  0.13979551,
         -0.06315858,  0.27288333]],

       [[-0.04972776, -0.16134055, -0.04497422, ..., -0.19434953,
          0.15166795,  0.07051366],
        [ 0.40138167, -0.7161993 ,  0.79605234, ..., -0.34071288,
          0.01467816, -0.28204957],
        [ 0.15850028, -0.13599601, -0.31225592, ..., -0.31121272,
         -0.1099389 , -0.5535948 ],
        ...,